name: Publish to npm

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'  # tag format: vX.X.X

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build project
        run: npm run build

      - name: Bump version in package.json
        run: |
          npm version ${{ github.ref_name }} --no-git-tag-version

      # setup OIDC between NPMJS.com and Github Action, can set it in NPM repo Settings
      - name: Publish to npm
        run: |
          npm publish
